apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: ns-ridpharm-webapp
  labels:
    app: app-ridpharm
    environment: production
    tier: frontend
    release: stable
spec:
  selector:
    app: app-ridpharm
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
