name: Secrets Leak Workflow

on:
  push:
    branches:
      - main

jobs:
  secrets-leak:
    runs-on: ubuntu-latest
    steps:
      - name: Use hardcoded AWS credentials
        env:
          AWS_ACCESS_KEY_ID: AKIAEXAMPLEKEY
          AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
        run: |
          echo "Deploying to AWS..."
          aws s3 cp ./file.txt s3://mybucket/
